package hgyw.com.bookshare.crud;

import com.annimon.stream.Stream;

import hgyw.com.bookshare.entities.Entity;

/**
 * Created by Yoni on 3/17/2016.
 */
public interface Crud {

    /**
     * Add new item to the data base. the id should be 0.
     * The id in the entity will be updated to the new id generated by the database.
     * @param item The item to add
     * @throws IllegalAccessException if item id is not 0.
     */
    void createEntity(Entity item);

    /**
     * Update item on the data base.
     * @param item The item to update
     * @throws java.util.NoSuchElementException if item of this entity with such id has not found.
     */
    void updateEntity(Entity item);

    /**
     * Delete an item from database. the method treats only to item type and id value.
     * @param item Item to delete
     * @throws java.util.NoSuchElementException if item of this entity with such id has not found.
     */
    void deleteEntity(Entity item);

    /**
     * Get a stream of all item of an entity.
     * @param entityClass The entity class
     * @param <T> The type of entity
     * @return Stream of type T contains the items
     */
    <T extends Entity> Stream<T> streamAll(Class<T> entityClass);

    /**
     * Retrieve an entity from database.
     * @param entityClass The entity class
     * @param id Item id
     * @param <T> The type of entity
     * @return Entity item of class T
     * @throws java.util.NoSuchElementException If database doesn't contain item of this entity and id.
     */
    <T extends Entity> T retrieveEntity(Class<T> entityClass, long id);
}
